version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: ./consulta-creditos-api
    container_name: springboot-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
  
  ui:
    build: ./consuta-creditos-ui
    container_name: ui_angular
    depends_on:
      - app
    ports:
      - "4200:4200"

volumes:
  pgdata:
